creating your first array

In [3]:
import numpy as np
temperatures=np.array([34,32,30,29,47])
print(temperatures)
print(("type:",type(temperatures)))


[34 32 30 29 47]
('type:', <class 'numpy.ndarray'>)


basic math on entire arrays at once

In [7]:
import numpy as np
prices=np.array([100,200,300,400])
prices_with_tax=prices*1.20
print(prices_with_tax)

[120. 240. 360. 480.]


2d arrays

In [9]:
import  numpy as np
marks=np.array([
    [88,89,70],
    [80,99,96],
    [87,78,87]
])
print(marks)
print("shape(rows,columns):",marks.shape)

[[88 89 70]
 [80 99 96]
 [87 78 87]]
shape(rows,columns): (3, 3)


useful built in function

In [1]:
import numpy as np
scores=np.array([45,67,77,90,50])
print("maximum score:",scores.max())
print("minimum score:",scores.min())
print("average score:",scores.mean())
print("total score:",scores.sum())
print("sorted scores:",np.sort(scores))

maximum score: 90
minimum score: 45
average score: 65.8
total score: 329
sorted scores: [45 50 67 77 90]


In [2]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "London", "Paris"]
}

df = pd.DataFrame(data)

print(df)

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris


In [10]:
import numpy as np
scores=np.array([45,67,77,90,50])
print("maximum score:",scores.max())
print("minimum score:",scores.min())
print("average score:",scores.mean())
print("total score:",scores.sum())
print("sorted scores:",np.sort(scores))

maximum score: 90
minimum score: 45
average score: 65.8
total score: 329
sorted scores: [45 50 67 77 90]


1d array

In [9]:
a = np.array([1,2,3])

print(a.ndim)

1


2d array

In [10]:
a = np.array([[1,2],[3,4]])

print(a.ndim)

2


check shape

In [21]:
import numpy as np
arr=np.array([
    [10,20,30]
    [40,50,60]
])
print(arr.shape)

<>:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\admin\AppData\Local\Temp\ipykernel_7644\4174709247.py:3: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [10,20,30]


TypeError: list indices must be integers or slices, not tuple